name: Continuous Integration

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Select an operating system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the project

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  # Choose appropriate .NET version

      - name: Restore dependencies
        run: dotnet restore  # Download dependencies

      - name: Build project
        run: dotnet build --configuration Release  # Create a project build

      - name: Run unit tests
        run: dotnet test --configuration Release --no-restore  # Run unit tests
